services:
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile.prod
    container_name: backend
    restart: unless-stopped
    env_file:
      - ./server/.env.prod
    ports:
      - "5000:5000"
    networks:
      - mern-net

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile.prod
      args:
        VITE_API_URL: http://backend:5000/api
    container_name: frontend
    restart: unless-stopped
    env_file:
      - ./client/.env.prod
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - mern-net

networks:
  mern-net:
    driver: bridge
